### ISSUE TITLE
Firmware Installation and default baud rate

### ISSUE THREAD

**Issue by jsphpl** [satshacopter/satshacopter-250X#1]
Hey Daniele, it seems like i can't find any instructions on the firmware installation. I assume all that needs to be done is to install [MultiWii](https://github.com/multiwii/multiwii-firmware) - can you provide a working default configuration for satshacopter please?

I am currently trying to get the copter here at Erfindergarden working. For this purpose, i'd like to connect using [Baseflight Configurator](https://chrome.google.com/webstore/detail/baseflight-configurator/mppkgnedeapfejgfimkdoninnofofigk?hl=en) or at least some serial terminal. Just to be sure: the boards that you made – at which baud rate are they communicating on the FTDI?

Thank you and best wishes from munich!
Joseph

**Comment by satshas** [comment]
Hi Joseph,

I suppose that you are trying to make the quadcopter work, but maybe you did not read the README of the repo which contains the link to the building manual?

Other than the main page you can find it in the following link, which is actually inside the repo if you make a clone:
https://github.com/satshacopter/satshacopter-250X/raw/master/docs/250X/satshacopter-250x-building-manual.pdf

On this manual, starting from page 25, you'll find the instructions on how to configure the config.h and upload the Multiwii.ino.

For the calibration you can use the Multiwii GUI, and the procedure is described  starting from page 48.

I never tried Baseflight and its GUI so I cannot help you on this, also because the drone was not intended to work with it, but maybe it can.

Let me know if the manual is enough or you need any other information ;)

Cheers from Kamp-Lintfort,
Daniele

**Comment by jsphpl** [comment]
Well the readme i read, of course. But i must admit i've been too lazy to read the entire build manual… Thanks for the hint! I'll let you know how it works out…
